//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace awaami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int id { get; set; }
        public Nullable<int> upvote { get; set; }
        public Nullable<int> downvote { get; set; }
        public Nullable<int> issue_category_id { get; set; }
        public string user_id { get; set; }
    
        public virtual Issue_category Issue_category { get; set; }
    }
}
