//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace awaami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string name { get; set; }
        public string cinic { get; set; }
        public string phone { get; set; }
        public string gender { get; set; }
        public string age { get; set; }
        public string upvote { get; set; }
        public string downvote { get; set; }
        public string isactive { get; set; }
    }
}
